name: Verify installation process
description: Install the binary and do extra checks.
branding:
  icon: 'terminal'
  color: 'green'

inputs:
  script:
    description: Validation script.
    required: true

runs:
  using: composite
  steps:
    - name: Add the action's path to the runner system path
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Run validation script
      run: ${{ inputs.script }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
